### ISSUE TITLE
requirements.txt error

### ISSUE THREAD

**Issue by flywire** [saufrecht/ledger-explorer#4]
```
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 19)) (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 19))
```

OS: Win10

**Comment by saufrecht** [comment]
This line shouldn't be there; it has something to do with a bug in one of the tools.  I've removed it from requirements.txt; please let me know if this resolves this issue.  Thanks for the report.

**Comment by flywire** [comment]
When the error occurred I removed the line and it went through to completion.
